### ISSUE TITLE
카멜 케이스 vs 스네이크 케이스

### ISSUE THREAD

**Issue by win9612** [Cocktail-Masters/Banana-Vote-BE#89]
## 문제 개요
 * `노션 API 명세서`와 `실제 백엔드 요청 시` 코드 네이밍 통일이 필요함
 * `스네이크 케이스`와 `카멜 케이스` 중 어느 것으로 통일할 것인가가 필요함 (둘중 한쪽은 케이스 변환을 자동으로 해주는 라이브러리나 어노테이션을 써야 함)

**Comment by win9612** [comment]
## 결론
 * JSON은 `스네이크 케이스`로 통일 (공식문서 권장사항)
 * 프론트엔드, 백엔드 각자 필요한 경우 변환해서 쓰기

**Comment by jsc7727** [comment]
## 프론트엔드
 * `axios intercepter` 에서 `camelize`를 사용해서 response.data를 `스네이크 케이스->카멜 케이스`로 변환하는 것으로 통일
 * 라이브러리 : https://www.npmjs.com/package/camelize

**Comment by YeoUlFox** [comment]
그렇군요
